"""TB-140 Teil 2 - die Fundstellen zu V2, gelesen von fundstellen_bauen.py (kein Modul des Repos).

Je Eintrag (kennung, datei, zeile, pruefstueck): das Pruefstueck muss in der Zeile stehen; den
Wortlaut liest fundstellen_bauen.py aus der Datei."""

S = "strategies/"
FUNDSTELLEN_V2 = [
    # --- gemeinsam --------------------------------------------------------------------------
    ("V2-01", "research/vorregistrierung/registerdaten.py", 102, 'GO_LIVE_SCHNITT = "2026-09-01"'),
    ("V2-02", "shared/kursdaten.py", 54, 'KURSSPALTEN = ["open", "high", "low", "close"]'),
    ("V2-03", "shared/kursdaten.py", 70, "return df[vorhanden].isna().any(axis=1)"),
    ("V2-04", "shared/kursdaten.py", 85, "bereinigt = df[~maske].reset_index(drop=True)"),
    ("V2-05", "shared/kursdaten.py", 86, "if melden:"),
    ("V2-06", "shared/strategy_paths.py", 155, '"DATA_DIR": paths.DATA_DIR,'),
    # --- Zuteilung nach R43 -------------------------------------------------------------------
    ("V2-07", "shared/zuteilung.py", 703, 'einstieg = pd.to_datetime(trades["entry_time"]).to_numpy()'),
    ("V2-08", "shared/zuteilung.py", 704, 'ausstieg = pd.to_datetime(trades["exit_time"]).to_numpy()'),
    ("V2-09", "shared/zuteilung.py", 714, "zeitpunkte = sorted(set(einstiege_je_zeit) | set(ausstiege_je_zeit))"),
    ("V2-10", "shared/zuteilung.py", 722, "for zeit in zeitpunkte:"),
    ("V2-11", "shared/zuteilung.py", 730, "capital += (result_value - allocation)"),
    ("V2-12", "shared/zuteilung.py", 731, "equity_curve.append({"),
    ("V2-13", "shared/zuteilung.py", 334, 'return int(np.searchsorted(self._tage, tag, side="left"))'),
    ("V2-14", "shared/zuteilung.py", 352, "anfang = max(0, ende - KORRELATIONSFENSTER_TAGE)"),
    ("V2-15", "shared/zuteilung.py", 400, "anfang = max(0, ende - LIQUIDITAETSFENSTER_TAGE)"),
    ("V2-16", "shared/zuteilung.py", 401, "werte = self._volumen[anfang:ende, self._spalte[symbol]]"),
    ("V2-17", "shared/zuteilung.py", 492, 'felder = [s for s in ("symbol", "entry_time", "exit_time", "entry_price",'),
    ("V2-18", "shared/zuteilung.py", 493, '"exit_price", "pnl_pct") if s in trades.columns]'),
    ("V2-19", "shared/zuteilung.py", 495, "self._zufall = [zufallsschluessel(self.seed, werte)"),
    ("V2-20", "shared/zuteilung.py", 540, "return sorted(positionen, key=lambda p: self._zufall[p])"),
    ("V2-21", "shared/zuteilung.py", 577, "gewinner = min(gruppe, key=lambda i: self._zufall[i])"),
    ("V2-22", "shared/zuteilung.py", 782, "else zuteiler.waehle(rest, _buch(open_positions, symbole), zeit))"),
    ("V2-23", "shared/zuteilung.py", 232, "df = wert[0] if isinstance(wert, tuple) else wert"),
    ("V2-24", "shared/zuteilung.py", 312, "self._renditen = kurse.pct_change(fill_method=None).to_numpy(dtype=float)"),
    # --- Benchmark und Kern: Bewertung ----------------------------------------------------------
    ("V2-25", "research/vorregistrierung/faltenplan.py", 326, "schnitt = date.fromisoformat(rd.GO_LIVE_SCHNITT)"),
    ("V2-26", "research/vorregistrierung/faltenplan.py", 312, "ende = bis_ausschliesslich"),
    ("V2-27", "research/vorregistrierung/benchmark.py", 280, 'bis = pd.Timestamp(f["bis_ausschliesslich"])'),
    ("V2-28", "research/vorregistrierung/benchmark.py", 290, "fenster = renditen[(renditen.index >= von) & (renditen.index < bis)]"),
    ("V2-29", "research/vorregistrierung/benchmark.py", 205, "return rahmen.pct_change().mean(axis=1, skipna=True).dropna()"),
    ("V2-30", "research/mtm_drawdown/mtm_kern.py", 147, "tage = tage[tage < pd.Timestamp(bis)]"),
    ("V2-31", "research/mtm_drawdown/messung.py", 156, 'bis=max(plan_bis, ereignisse["exit_time"].max().normalize() + mtm_kern.EIN_TAG))'),
    ("V2-32", "research/mtm_drawdown/mtm_kern.py", 298, 'tage_in = pfad[(pfad.index >= von) & (pfad.index < bis)]'),
    ("V2-33", "research/mtm_drawdown/mtm_kern.py", 167, "spalten[symbol] = eigene.ffill()"),
    # --- elliott_wave (1h) ----------------------------------------------------------------------
    ("V2-34", S + "elliott_wave/multi_symbol_optimise.py", 53, "def load_all_symbol_data() -> dict:"),
    ("V2-35", S + "elliott_wave/multi_symbol_optimise.py", 61, 'csv_path = os.path.join(DATA_DIR, f"{symbol}_{INTERVAL}.csv")'),
    ("V2-36", S + "elliott_wave/multi_symbol_optimise.py", 72, "df, _gestrichen = entferne_unvollstaendige(df, symbol=symbol,"),
    ("V2-37", S + "elliott_wave/multi_symbol_optimise.py", 83, "if len(df) < MIN_HISTORY_HOURS:"),
    ("V2-38", S + "elliott_wave/backtest_elliott.py", 82, 'future = price_df[price_df["open_time"] > entry_time].head(max_hold_hours)'),
    ("V2-39", S + "elliott_wave/backtest_elliott.py", 98, "last_row = future.iloc[-1]"),
    ("V2-40", S + "elliott_wave/backtest_elliott.py", 99, 'return {"exit_time": last_row["open_time"], "exit_price": last_row["close"], "result": "time_exit"}'),
    ("V2-41", S + "elliott_wave/backtest_elliott.py", 100, 'return {"exit_time": None, "exit_price": entry_price, "result": "no_data"}'),
    ("V2-42", S + "elliott_wave/elliott_wave_counter.py", 343, 'known = candidates[candidates["confirm_idx"] <= run_bar]'),
    ("V2-43", S + "elliott_wave/elliott_wave_counter.py", 358, 'row["entry_idx"] = int(run_bar)'),
    ("V2-44", S + "elliott_wave/zigzag_indicator.py", 163, "for i in range(1, len(df)):"),
    ("V2-45", S + "elliott_wave/equity_simulation.py", 78, "trades = get_trades_for_symbol(price_df, deviation_pct)"),
    # --- t3_supertrend (4h) ---------------------------------------------------------------------
    ("V2-46", S + "t3_supertrend/multi_symbol_optimise.py", 57, 'csv_path = os.path.join(DATA_DIR, f"{symbol}_{INTERVAL}.csv")'),
    ("V2-47", S + "t3_supertrend/multi_symbol_optimise.py", 68, "df, _gestrichen = entferne_unvollstaendige(df, symbol=symbol,"),
    ("V2-48", S + "t3_supertrend/multi_symbol_optimise.py", 79, 'timespan_days = (df["open_time"].max() - df["open_time"].min()).days'),
    ("V2-49", S + "t3_supertrend/backtest_trend.py", 101, "for i in range(1, len(data)):"),
    ("V2-50", S + "t3_supertrend/backtest_trend.py", 121, 'exit_price = position["stop_price"] if stop_hit else close[i]'),
    ("V2-51", S + "t3_supertrend/backtest_trend.py", 127, "trades.append({"),
    ("V2-52", S + "t3_supertrend/backtest_trend.py", 137, "return pd.DataFrame(trades)"),
    ("V2-53", S + "t3_supertrend/indicators.py", 23, "e1 = series.ewm(span=length, adjust=False).mean()"),
    ("V2-54", S + "t3_supertrend/regime_filter.py", 43, 'left_on="entry_time", right_on="open_time", direction="backward",'),
    ("V2-55", "shared/regimewache.py", 86, 'btc = all_data.get(SYMBOL) if hasattr(all_data, "get") else None'),
    ("V2-56", S + "t3_supertrend/equity_simulation.py", 65, "trades = get_trades_for_symbol(price_df, t3_fast, t3_slow, adx_threshold, stop_loss_pct)"),
    # --- rsi2_crypto (1d) -----------------------------------------------------------------------
    ("V2-57", S + "rsi2_crypto/multi_symbol_optimise.py", 64, 'csv_path = os.path.join(DATA_DIR, f"{symbol}_{INTERVAL}.csv")'),
    ("V2-58", S + "rsi2_crypto/multi_symbol_optimise.py", 75, "df, _gestrichen = entferne_unvollstaendige(df, symbol=symbol,"),
    ("V2-59", S + "rsi2_crypto/multi_symbol_optimise.py", 85, 'timespan_days = (df["open_time"].max() - df["open_time"].min()).days'),
    ("V2-60", S + "rsi2_crypto/equity_simulation.py", 63, "trades = get_trades_for_symbol(price_df, rsi_threshold, sma_trend_period, stop_loss_pct)"),
    ("V2-61", S + "rsi2_crypto/backtest_rsi2.py", 92, "while i < n:"),
    ("V2-62", S + "rsi2_crypto/backtest_rsi2.py", 107, "max_offset = min(MAX_HOLD_DAYS, n - 1 - i)"),
    ("V2-63", S + "rsi2_crypto/backtest_rsi2.py", 117, 'exit_idx, exit_price, result = idx, close[idx], "time_exit"'),
    ("V2-64", S + "rsi2_crypto/backtest_rsi2.py", 120, "if exit_idx is None:"),
    ("V2-65", S + "rsi2_crypto/backtest_rsi2.py", 121, "break"),
    ("V2-66", S + "rsi2_crypto/indicators.py", 21, "return series.rolling(window=window).mean()"),
    # --- turtle_soup_crypto (1d) -------------------------------------------------------------------
    ("V2-67", S + "turtle_soup_crypto/multi_symbol_optimise.py", 47, 'csv_path = os.path.join(DATA_DIR, f"{symbol}_{INTERVAL}.csv")'),
    ("V2-68", S + "turtle_soup_crypto/multi_symbol_optimise.py", 58, "df, _gestrichen = entferne_unvollstaendige(df, symbol=symbol,"),
    ("V2-69", S + "turtle_soup_crypto/multi_symbol_optimise.py", 67, 'timespan_days = (df["open_time"].max() - df["open_time"].min()).days'),
    ("V2-70", S + "turtle_soup_crypto/equity_simulation.py", 54, "trades = get_trades_for_symbol(price_df, donchian_period, stop_mode)"),
    ("V2-71", S + "turtle_soup_crypto/backtest_turtle_soup.py", 130, "while i < n:"),
    ("V2-72", S + "turtle_soup_crypto/backtest_turtle_soup.py", 154, "max_offset = min(max_hold_days, n - 1 - i)"),
    ("V2-73", S + "turtle_soup_crypto/backtest_turtle_soup.py", 161, 'exit_idx, exit_price, result = idx, close[idx], "time_exit"'),
    ("V2-74", S + "turtle_soup_crypto/backtest_turtle_soup.py", 164, "if exit_idx is None:"),
    ("V2-75", S + "turtle_soup_crypto/backtest_turtle_soup.py", 165, "break"),
    ("V2-76", S + "turtle_soup_crypto/indicators.py", 15, "return low.shift(1).rolling(window=period).min()"),
    # --- volatility_breakout_crypto (1d) ------------------------------------------------------------
    ("V2-77", S + "volatility_breakout_crypto/multi_symbol_optimise.py", 49, 'csv_path = os.path.join(DATA_DIR, f"{symbol}_{INTERVAL}.csv")'),
    ("V2-78", S + "volatility_breakout_crypto/multi_symbol_optimise.py", 60, "df, _gestrichen = entferne_unvollstaendige(df, symbol=symbol,"),
    ("V2-79", S + "volatility_breakout_crypto/multi_symbol_optimise.py", 70, 'timespan_days = (df["open_time"].max() - df["open_time"].min()).days'),
    ("V2-80", S + "volatility_breakout_crypto/equity_simulation.py", 73, "trades = get_trades_for_symbol(price_df, stop_loss_pct, max_hold_days, use_volume_filter,"),
    ("V2-81", S + "volatility_breakout_crypto/backtest_breakout.py", 135, "while i < n:"),
    ("V2-82", S + "volatility_breakout_crypto/backtest_breakout.py", 157, "max_offset = min(max_hold_days, n - 1 - i)"),
    ("V2-83", S + "volatility_breakout_crypto/backtest_breakout.py", 167, "if exit_idx is None:"),
    ("V2-84", S + "volatility_breakout_crypto/backtest_breakout.py", 168, "break"),
    ("V2-85", S + "volatility_breakout_crypto/indicators.py", 19, "middle = close.rolling(window=period).mean()"),
    ("V2-86", S + "volatility_breakout_crypto/regime_filter.py", 39, 'left_on="entry_time", right_on="open_time", direction="backward",'),
    # --- Zaehlung und Meldung der Streichung ------------------------------------------------------
    ("V2-87", "shared/kursdaten.py", 82, "anzahl = int(maske.sum())"),
    ("V2-88", "shared/kursdaten.py", 104, "self.je_symbol[symbol] = anzahl"),
    ("V2-89", "shared/kursdaten.py", 121, "print(text)"),
    # --- elliott_wave_stocks (1d) ------------------------------------------------------------------
    ("V2-90", S + "elliott_wave_stocks/multi_symbol_optimise.py", 60, "def load_all_symbol_data() -> dict:"),
    ("V2-91", S + "elliott_wave_stocks/multi_symbol_optimise.py", 70, 'csv_path = os.path.join(DATA_DIR, f"{symbol}_{INTERVAL}.csv")'),
    ("V2-92", S + "elliott_wave_stocks/multi_symbol_optimise.py", 81, "df, _gestrichen = entferne_unvollstaendige(df, symbol=symbol,"),
    ("V2-93", S + "elliott_wave_stocks/multi_symbol_optimise.py", 82, "melden=False)"),
    ("V2-94", S + "elliott_wave_stocks/multi_symbol_optimise.py", 83, "_luecken.erfasse(symbol, _gestrichen)"),
    ("V2-95", S + "elliott_wave_stocks/multi_symbol_optimise.py", 102, "_luecken.melde()"),
    ("V2-96", S + "elliott_wave_stocks/multi_symbol_optimise.py", 54, "RECENT_YEARS_ONLY = 10"),
    ("V2-97", S + "elliott_wave_stocks/multi_symbol_optimise.py", 93, 'cutoff = df["open_time"].max() - pd.DateOffset(years=RECENT_YEARS_ONLY)'),
    ("V2-98", S + "elliott_wave_stocks/multi_symbol_optimise.py", 94, 'df = df[df["open_time"] >= cutoff].reset_index(drop=True)'),
    ("V2-99", S + "elliott_wave_stocks/multi_symbol_optimise.py", 96, 'timespan_days = (df["open_time"].max() - df["open_time"].min()).days'),
    ("V2-100", S + "elliott_wave_stocks/backtest_elliott.py", 91, 'future = price_df[price_df["open_time"] > entry_time].head(max_hold_hours)'),
    ("V2-101", S + "elliott_wave_stocks/backtest_elliott.py", 107, "last_row = future.iloc[-1]"),
    ("V2-102", S + "elliott_wave_stocks/backtest_elliott.py", 108, '"exit_price": last_row["close"], "result": "time_exit"}'),
    ("V2-103", S + "elliott_wave_stocks/elliott_wave_counter.py", 343, 'known = candidates[candidates["confirm_idx"] <= run_bar]'),
    ("V2-104", S + "elliott_wave_stocks/zigzag_indicator.py", 160, "last_pivot_idx = 0"),
    ("V2-105", S + "elliott_wave_stocks/equity_simulation.py", 107, "luecke = combined[preisspalten].isna().any(axis=1)"),
    ("V2-106", S + "elliott_wave_stocks/equity_simulation.py", 111, "combined = combined[~luecke]"),
    # --- rsi2_mean_reversion (1d) --------------------------------------------------------------------
    ("V2-107", S + "rsi2_mean_reversion/multi_symbol_optimise.py", 65, 'csv_path = os.path.join(DATA_DIR, f"{symbol}_{INTERVAL}.csv")'),
    ("V2-108", S + "rsi2_mean_reversion/multi_symbol_optimise.py", 76, "df, _gestrichen = entferne_unvollstaendige(df, symbol=symbol,"),
    ("V2-109", S + "rsi2_mean_reversion/multi_symbol_optimise.py", 78, "_luecken.erfasse(symbol, _gestrichen)"),
    ("V2-110", S + "rsi2_mean_reversion/multi_symbol_optimise.py", 52, "RECENT_YEARS_ONLY = 10"),
    ("V2-111", S + "rsi2_mean_reversion/multi_symbol_optimise.py", 86, 'timespan_days = (df["open_time"].max() - df["open_time"].min()).days'),
    ("V2-112", S + "rsi2_mean_reversion/multi_symbol_optimise.py", 93, 'entry_cutoff = df["open_time"].max() - pd.DateOffset(years=RECENT_YEARS_ONLY)'),
    ("V2-113", S + "rsi2_mean_reversion/equity_simulation.py", 74, "trades = get_trades_for_symbol(df_ind, entry_cutoff, rsi_threshold, stop_loss_pct,"),
    ("V2-114", S + "rsi2_mean_reversion/backtest_rsi2.py", 131, 'start_i = max(start_i, int((df["open_time"] < entry_cutoff).sum()))'),
    ("V2-115", S + "rsi2_mean_reversion/backtest_rsi2.py", 150, "max_offset = min(MAX_HOLD_DAYS, n - 1 - i)"),
    ("V2-116", S + "rsi2_mean_reversion/backtest_rsi2.py", 163, "if exit_idx is None:"),
    ("V2-117", S + "rsi2_mean_reversion/backtest_rsi2.py", 164, "break"),
    ("V2-118", S + "rsi2_mean_reversion/indicators.py", 23, "return series.rolling(window=window).mean()"),
    ("V2-119", S + "rsi2_mean_reversion/equity_simulation.py", 97, "luecke = combined[preisspalten].isna().any(axis=1)"),
    # --- turtle_soup_stocks (1d) ---------------------------------------------------------------------
    ("V2-120", S + "turtle_soup_stocks/multi_symbol_optimise.py", 54, 'csv_path = os.path.join(DATA_DIR, f"{symbol}_{INTERVAL}.csv")'),
    ("V2-121", S + "turtle_soup_stocks/multi_symbol_optimise.py", 65, "df, _gestrichen = entferne_unvollstaendige(df, symbol=symbol,"),
    ("V2-122", S + "turtle_soup_stocks/multi_symbol_optimise.py", 67, "_luecken.erfasse(symbol, _gestrichen)"),
    ("V2-123", S + "turtle_soup_stocks/multi_symbol_optimise.py", 46, "RECENT_YEARS_ONLY = 10"),
    ("V2-124", S + "turtle_soup_stocks/multi_symbol_optimise.py", 74, 'timespan_days = (df["open_time"].max() - df["open_time"].min()).days'),
    ("V2-125", S + "turtle_soup_stocks/multi_symbol_optimise.py", 81, 'entry_cutoff = df["open_time"].max() - pd.DateOffset(years=RECENT_YEARS_ONLY)'),
    ("V2-126", S + "turtle_soup_stocks/equity_simulation.py", 79, "trades = get_trades_for_symbol(df, entry_cutoff, donchian_period, stop_mode)"),
    ("V2-127", S + "turtle_soup_stocks/backtest_turtle_soup.py", 122, 'start_i = max(start_i, int((df["open_time"] < entry_cutoff).sum()))'),
    ("V2-128", S + "turtle_soup_stocks/backtest_turtle_soup.py", 150, "max_offset = min(max_hold_days, n - 1 - i)"),
    ("V2-129", S + "turtle_soup_stocks/backtest_turtle_soup.py", 160, "if exit_idx is None:"),
    ("V2-130", S + "turtle_soup_stocks/backtest_turtle_soup.py", 161, "break"),
    ("V2-131", S + "turtle_soup_stocks/indicators.py", 15, "return low.shift(1).rolling(window=period).min()"),
    ("V2-132", S + "turtle_soup_stocks/equity_simulation.py", 99, "luecke = combined[preisspalten].isna().any(axis=1)"),
    # --- volatility_breakout (1d) ---------------------------------------------------------------------
    ("V2-133", S + "volatility_breakout/multi_symbol_optimise.py", 61, 'csv_path = os.path.join(DATA_DIR, f"{symbol}_{INTERVAL}.csv")'),
    ("V2-134", S + "volatility_breakout/multi_symbol_optimise.py", 72, "df, _gestrichen = entferne_unvollstaendige(df, symbol=symbol,"),
    ("V2-135", S + "volatility_breakout/multi_symbol_optimise.py", 74, "_luecken.erfasse(symbol, _gestrichen)"),
    ("V2-136", S + "volatility_breakout/multi_symbol_optimise.py", 50, "RECENT_YEARS_ONLY = 10"),
    ("V2-137", S + "volatility_breakout/multi_symbol_optimise.py", 82, 'timespan_days = (df["open_time"].max() - df["open_time"].min()).days'),
    ("V2-138", S + "volatility_breakout/multi_symbol_optimise.py", 89, 'entry_cutoff = df["open_time"].max() - pd.DateOffset(years=RECENT_YEARS_ONLY)'),
    ("V2-139", S + "volatility_breakout/equity_simulation.py", 75, "trades = get_trades_for_symbol(df_ind, entry_cutoff, stop_loss_pct, max_hold_days, use_volume_filter,"),
    ("V2-140", S + "volatility_breakout/backtest_breakout.py", 172, 'start_i = max(start_i, int((df["open_time"] < entry_cutoff).sum()))'),
    ("V2-141", S + "volatility_breakout/backtest_breakout.py", 198, "max_offset = min(max_hold_days, n - 1 - i)"),
    ("V2-142", S + "volatility_breakout/backtest_breakout.py", 208, "if exit_idx is None:"),
    ("V2-143", S + "volatility_breakout/backtest_breakout.py", 209, "break"),
    ("V2-144", S + "volatility_breakout/indicators.py", 25, "middle = close.rolling(window=period).mean()"),
    ("V2-145", S + "volatility_breakout/equity_simulation.py", 99, "luecke = combined[preisspalten].isna().any(axis=1)"),
    # --- Lesestellen nur im __main__-Block (nicht im Lauf) --------------------------------------------
    ("V2-146", S + "elliott_wave_stocks/backtest_elliott.py", 212, 'if __name__ == "__main__":'),
    ("V2-147", S + "elliott_wave_stocks/backtest_elliott.py", 216, 'price_df = pd.read_csv(os.path.join(DATA_DIR, "AAPL_1d.csv"), parse_dates=["open_time"])'),
    ("V2-148", S + "rsi2_mean_reversion/backtest_rsi2.py", 182, 'if __name__ == "__main__":'),
    ("V2-149", S + "turtle_soup_stocks/backtest_turtle_soup.py", 179, 'if __name__ == "__main__":'),
    ("V2-150", S + "volatility_breakout/backtest_breakout.py", 227, 'if __name__ == "__main__":'),
    ("V2-151", S + "rsi2_mean_reversion/buy_and_hold_benchmark.py", 34, 'df = pd.read_csv(csv_path, parse_dates=["open_time"])'),
    # --- elliott_wave (1h): Zaehlung der Zeilen ------------------------------------------------------
    ("V2-152", S + "elliott_wave/multi_symbol_optimise.py", 50, "MIN_HISTORY_HOURS = 17520"),
    # --- Lader-Kopfzeilen und Zeitrahmen der Kursdatei ------------------------------------------------
    ("V2-153", S + "t3_supertrend/multi_symbol_optimise.py", 50, "def load_all_symbol_data() -> dict:"),
    ("V2-154", S + "rsi2_crypto/multi_symbol_optimise.py", 59, "def load_all_symbol_data() -> dict:"),
    ("V2-155", S + "turtle_soup_crypto/multi_symbol_optimise.py", 42, "def load_all_symbol_data() -> dict:"),
    ("V2-156", S + "volatility_breakout_crypto/multi_symbol_optimise.py", 44, "def load_all_symbol_data() -> dict:"),
    ("V2-157", S + "rsi2_mean_reversion/multi_symbol_optimise.py", 55, "def load_all_symbol_data() -> dict:"),
    ("V2-158", S + "turtle_soup_stocks/multi_symbol_optimise.py", 49, "def load_all_symbol_data() -> dict:"),
    ("V2-159", S + "volatility_breakout/multi_symbol_optimise.py", 53, "def load_all_symbol_data() -> dict:"),
    ("V2-160", "shared/fetch_multi_data.py", 48, "INTERVAL = Client.KLINE_INTERVAL_1HOUR"),
    ("V2-161", S + "t3_supertrend/fetch_4h_data.py", 51, "INTERVAL = Client.KLINE_INTERVAL_4HOUR"),
    ("V2-162", S + "elliott_wave_stocks/fetch_stock_data.py", 67, 'INTERVAL = "1d"'),
    ("V2-163", S + "rsi2_crypto/multi_symbol_optimise.py", 45, 'INTERVAL = "1d"'),
    ("V2-164", S + "turtle_soup_crypto/multi_symbol_optimise.py", 31, 'INTERVAL = "1d"'),
    ("V2-165", S + "volatility_breakout_crypto/multi_symbol_optimise.py", 34, 'INTERVAL = "1d"'),
    ("V2-166", S + "rsi2_mean_reversion/multi_symbol_optimise.py", 38, 'INTERVAL = "1d"'),
    ("V2-167", S + "turtle_soup_stocks/multi_symbol_optimise.py", 37, 'INTERVAL = "1d"'),
    ("V2-168", S + "volatility_breakout/multi_symbol_optimise.py", 41, 'INTERVAL = "1d"'),
]
